// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"github.com/dddong3/Bid_Backend/auctionitem"
)

type AuctionItemConnection struct {
	Nodes    []*auctionitem.AuctionItem `json:"nodes"`
	PageInfo *PageInfo                  `json:"pageInfo"`
}

type PageInfo struct {
	HasNextPage bool `json:"hasNextPage"`
	HasPrevPage bool `json:"hasPrevPage"`
	TotalCount  int  `json:"totalCount"`
}

type Query struct {
}

type SingleAuctionItem struct {
	Node *auctionitem.AuctionItem `json:"node"`
}
